---
title: "DirectRepeateR Tutorial"
author: "Megan Copeland, Andres Barboza, Heath Blackmon"
date: 'Last updated: `r Sys.Date()`'
output:
  html_document:
    toc: true
    df_print: paged
  html_vignette:
    fig_caption: true
    toc: true
  pdf_document: default
vignette: "%\\VignetteIndexEntry{DirectRepeatR Tutorial} %\\VignetteEncoding{UTF-8}
  %\\VignetteEngine{knitr::rmarkdown}\n"
---

## Introduction

The `DirectRepeateR` package is designed to identify, annotate, and visualize direct repeat sequences within genome assemblies. This vignette provides a comprehensive guide to using the core functions of the package, including `GetRepeats` for repeat detection and `PlotRepeats` for visualization.

## Installing DirectRepeateR

You can install the most recent version of `DirectRepeateR` from GitHub using the `devtools` package:

```r
library(devtools)
install_github("coleoguy/DirectRepeateR",
                build_vignettes = TRUE)
                library(DirectRepeateR)
```
Direct repeats are identical DNA sequences oriented in the same direction and occur in realtively close proximity within a genome. These repeats are significant due to their involvement in genome stability/instability. For example, direct repeats play are the foundation of the single-strand annealing (SSA) DNA repair pathway. This pathway repairs double-strand DNA breaks by annealing complementary direct repeats, leading to the deletion of DNA intervening between the repeats. As such, direct repeats can profoundly influence genomic integrity, gene function, and evolutionary processes. Despite this biological importance, direct repeats are understudied compared to other repeat types, partly due to a lack of targeted annotation tools—highlighting the need for specialized methods, like DirectRepeateR, for their accurate detection and annotation.

## GetRepeats Function

The GetRepeats() function searches for direct repeats in a FASTA file by calling a compiled C++ routine. It writes CSV files for each chromosome into the chromosome_results folder. It then merges these files into a single table, filtering out repeats below a specified minimum length. There is option to specify the path where you can save out the merged results.

### Example Usage

```r
results <- GetRepeats(
  file         = "PATH/TO/genome.fa",
  query_length = 25, 
  maxdist      = 20000, 
  minlength    = 50,
  merged_csv   = "merged_results.csv"
)

```

### Parameters

- **file**: A character string specifying the path to the genome assembly file in FASTA format. We recommend using a FASTA file that has been filtered to remove all small, unplaced contigs/scaffolds.
- **query_length**: An integer specifying the length of the query sequence used to search for direct repeats. The genome sequence is segmented into subsequences of this length to identify repeated patterns. Default is 25 if not specified.
- **maxdist**: An integer specifying the maximum distance between repeat copies within which the function will search for direct repeats. This sets a limit on how far apart the repeated sequences can be. Default is 20000 if not specified.
- **minlength**: An integer specifying the minimum length of sequences to be considered as direct repeats. Only repeats of this length or longer will be detected.  While it can be any value, repeats are only captured at natural multiples of the query length (e.g., a query of 10 with minlength 85 will still detect repeats of at least 90). Default is 25 if not specified.
- **merged_csv**: (Optional) A character string specifying the path for the output file.

### Output
The intermediate chromosome CSV files will be saved out to the chromosome_results folder. These files will be named according to the sequence that those results correspond to and will have four columns:

1. **Start**: Start position of the first occurrence of the repeat.
2. **End**: End position of the first occurrence of the repeat.
3. **Match_Start**: Start position of the second occurrence of the repeat (the repeat copy).
4. **Match_End**: End position of the second occurrence of the repeat (the repeat copy).

The final, merged output .csv file will be saved out as specified in the parameters. If not specified, it will be saved in your working directory. This file will have a five column format:

1. **Chromosome**: Chromosomal location of the repeat.
1. **Start**: Start position of the first occurrence of the repeat.
2. **End**: End position of the first occurrence of the repeat.
3. **Match_Start**: Start position of the second occurrence of the repeat (the repeat copy).
4. **Match_End**: End position of the second occurrence of the repeat (the repeat copy).

## ConvertToGFF Function

The `ConvertToGFF` function is designed to convert the output from `GetRepeats`function into a GFF (General Feature Format) file. The function processes each row of the final_output data frame, which contains location information for the detected repeat sequences, and generates three corresponding GFF entries: one for the full length of the repeat, representing the region from the start of the first copy to the end of the second copy; one for the first detected repeat copy; and one for the second detected repeat copy. The gff file is written out as a text file and saved in a results folder in the working directory.

### Example Usage

```r
gff_output <- ConvertToGFF(data = merged_results)
```
### Parameters

- **data**: The merged results data frame generated by the `GetRepeats` function, containing details about the locations of direct repeats within a genome assembly.

## PlotRepeats Function

The `PlotRepeats` function visualizes the density of direct repeats across chromosomes using a sliding window approach. This section explains how to use it and customize the visualization.

### Example Usage

```r
PlotRepeats(merged_results, window_size = 200000, step_size = 200000)
```

### Parameters

- **data**: The merged results data frame generated by the `GetRepeats` function, containing details about the locations of direct repeats within a genome assembly.
- **window_size**: An integer specifying the size of the sliding window used to count the number of repeats. Default is 200,000 base pairs.
- **step_size**: An integer specifying the step size for the sliding window. This defines the interval at which the window moves along the chromosome. Default is 200,000 base pairs.

### Output

The function generates and displays line plots for each chromosome, showing a the number of repeats within each window along the chromosome's length.

## Conclusion

The `DirectRepeateR` package provides tools for identifying and visualizing direct repeats in genomic data. By following this vignette, you should be able to use the each of the functions to analyze direct repeats within genome assemblies.
