// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#include <string> 
// Forward declaration for run_combined_cpp
void run_combined_cpp(const std::string &fasta_path, int query_length, int maxdist);

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_combined_cpp
// Hard-coded outdir = "chromosome_results", no user option. void run_combined_cpp(const std::string& fasta_path, int query_length, int maxdist);
RcppExport SEXP _DirectRepeateR_run_combined_cpp(SEXP fasta_pathSEXP, SEXP query_lengthSEXP, SEXP maxdistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type fasta_path(fasta_pathSEXP);
    Rcpp::traits::input_parameter< int >::type query_length(query_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type maxdist(maxdistSEXP);
    rcpp_result_gen = Rcpp::wrap(run_combined_cpp(fasta_path, query_length, maxdist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DirectRepeateR_run_combined_cpp", (DL_FUNC) &_DirectRepeateR_run_combined_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DirectRepeateR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
