# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_combined_cpp <- function(fasta_path, query_length, maxdist, outdir) {
    .Call(`_DirectRepeateR_run_combined_cpp`, fasta_path, query_length, maxdist, outdir)
}

